probe_info_service: refactor testing code
This CL centralizes test materials to files in
`py/probe_info_service/app_engine/testdata/` so that they can be
shared across different test cases.

BUG=b:146768256
TEST=./deploy/probe_info_service unittest

Change-Id: Ie398ec4a8a4f36a6681abeb5aebb1f073d1a7a55
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/factory/+/2265113
Reviewed-by: Liang-Chieh Chen <jamesqaq@chromium.org>
Tested-by: Yong Hong <yhong@chromium.org>
Commit-Queue: Yong Hong <yhong@chromium.org>

diff --git a/py/probe_info_service/app_engine/testdata/fake_runtime_probe b/py/probe_info_service/app_engine/testdata/fake_runtime_probe
--- a/py/probe_info_service/app_engine/testdata/fake_runtime_probe
+++ b/py/probe_info_service/app_engine/testdata/fake_runtime_probe
@@ -3,6 +3,19 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
+# Standard output is controlled by the tester.
 echo "${FAKE_RUNTIME_PROBE_STDOUT}"
+
+# Standard error contains the source material passed from the
+# runtime_probe_wrapper.
 echo "$@" >&2
+echo "=====" >&2
+for arg in "$@"; do
+  if [[ "${arg}" = "--config_file_path="* ]]; then
+    config_file_path="${arg#*=}"
+    cat "${config_file_path}" >&2
+  fi
+done
+
+# Return code is controlled by the tester.
 exit "${FAKE_RUNTIME_PROBE_RETURN_CODE}"
